"use client";

import { useState, useEffect, useCallback } from "react";
import { getCurrentUser } from "@/lib/auth";
import Header from "@/components/Header";
import Link from "next/link";

interface Transfer {
  id: string;
  asset_id: string;
  asset_name?: string;
  asset_tag?: string;
  from_department: string;
  to_department: string;
  requested_by: string;
  requested_by_name?: string;
  reason?: string;
  status: string;
  request_date: string;
  approved_by?: string;
  approved_date?: string;
}

export default function TransfersPage() {
  const [user, setUser] = useState<any>(null);
  const [transfers, setTransfers] = useState<Transfer[]>([]);
  const [loading, setLoading] = useState(true);
  const [filterStatus, setFilterStatus] = useState("");
  const [showApprovalModal, setShowApprovalModal] = useState(false);
  const [selectedTransfer, setSelectedTransfer] = useState<Transfer | null>(
    null
  );
  const [showDetailsModal, setShowDetailsModal] = useState(false);

  const fetchTransfers = useCallback(async () => {
    try {
      const params = new URLSearchParams();
      if (filterStatus) params.append("status", filterStatus);

      const response = await fetch(
        `http://localhost:8000/api/transfer/index.php?${params}`
      );
      const data = await response.json();

      if (data.success) {
        setTransfers(data.transfers);
      } else {
        console.error("Failed to fetch transfers:", data.error);
      }
    } catch (error) {
      console.error("Error fetching transfers:", error);
    } finally {
      setLoading(false);
    }
  }, [filterStatus]);

  useEffect(() => {
    // Only run on client side to avoid hydration mismatch
    const currentUser = getCurrentUser();
    setUser(currentUser);
  }, []);

  useEffect(() => {
    if (user) {
      fetchTransfers();
    }
  }, [user, fetchTransfers]);

  const handleLogout = () => {
    localStorage.removeItem("currentUser");
    window.location.href = "/";
  };

  const handleViewDetails = (transfer: Transfer) => {
    setSelectedTransfer(transfer);
    setShowDetailsModal(true);
  };

  const generatePDF = async () => {
    try {
      // Dynamic import for client-side only
      const jsPDF = (await import("jspdf")).default;
      await import("jspdf-autotable");

      const doc = new jsPDF();

      // Add logo
      const logoResponse = await fetch("/logo.png");
      const logoData = await logoResponse.blob();
      const reader = new FileReader();
      reader.readAsDataURL(logoData);
      reader.onloadend = () => {
        const base64data = reader.result;
        doc.addImage(base64data, "PNG", 14, 15, 30, 30);

        // Add header
        const pageWidth = doc.internal.pageSize.getWidth();
        doc.setFontSize(20);
        doc.text("TUM Procurement System", pageWidth / 2, 22, {
          align: "center",
        });
        doc.setFontSize(16);
        doc.text("Asset Transfers Report", pageWidth / 2, 32, {
          align: "center",
        });

        // Add generation date
        doc.setFontSize(10);
        doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 42, {
          align: "left",
        });
        doc.text(`Generated by: ${user?.name || "Unknown User"}`, 14, 48, {
          align: "left",
        });

        // Add filters info if any are applied
        let yPosition = 58;
        if (filterStatus) {
          doc.setFontSize(12);
          doc.text("Applied Filters:", 14, yPosition);
          yPosition += 8;
          doc.setFontSize(10);
          doc.text(`Status: ${filterStatus}`, 14, yPosition);
          yPosition += 10;
        }

        // Prepare table data
        const tableData = filteredTransfers.map((transfer) => [
          transfer.asset_name || "Unknown Asset",
          transfer.asset_tag || "N/A",
          transfer.from_department,
          transfer.to_department,
          transfer.status,
          new Date(transfer.request_date).toLocaleDateString(),
          transfer.requested_by_name || "Unknown",
        ]);

        // Add table
        (doc as any).autoTable({
          head: [
            [
              "Asset Name",
              "Asset Tag",
              "From Dept",
              "To Dept",
              "Status",
              "Request Date",
              "Requested By",
            ],
          ],
          body: tableData,
          startY: yPosition,
          styles: {
            fontSize: 8,
            cellPadding: 2,
          },
          headStyles: {
            fillColor: [66, 139, 202],
            textColor: 255,
            fontStyle: "bold",
          },
          columnStyles: {
            0: { cellWidth: 30 }, // Asset Name
            1: { cellWidth: 25 }, // Asset Tag
            2: { cellWidth: 25 }, // From Dept
            3: { cellWidth: 25 }, // To Dept
            4: { cellWidth: 20 }, // Status
            5: { cellWidth: 25 }, // Request Date
            6: { cellWidth: 25 }, // Requested By
          },
          margin: { top: yPosition, right: 14, bottom: 20, left: 14 },
          didDrawPage: function (data: any) {
            // Footer
            const str = `Page ${data.pageNumber}`;
            doc.setFontSize(10);
            const pageSize = doc.internal.pageSize;
            const pageHeight = pageSize.height
              ? pageSize.height
              : pageSize.getHeight();
            doc.text(str, data.settings.margin.left, pageHeight - 10);

            // Total count
            if (data.pageNumber === 1) {
              doc.text(
                `Total Transfers: ${filteredTransfers.length}`,
                pageSize.width - 50,
                pageHeight - 10
              );
            }
          },
        });

        // Save the PDF
        const fileName = `TUM_Transfers_Report_${
          new Date().toISOString().split("T")[0]
        }.pdf`;
        doc.save(fileName);
      };
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("Failed to generate PDF. Please try again.");
    }
  };

  const handleApprove = async (transferId: string) => {
    try {
      const response = await fetch(
        "http://localhost:8000/api/transfer/update.php",
        {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            id: transferId,
            status: "Approved",
          }),
        }
      );

      const data = await response.json();

      if (data.success) {
        await fetchTransfers(); // Refresh the list
        setShowApprovalModal(false);
        setSelectedTransfer(null);
      } else {
        alert("Failed to approve transfer: " + (data.error || "Unknown error"));
      }
    } catch (error) {
      console.error("Error approving transfer:", error);
      alert("Failed to approve transfer. Please try again.");
    }
  };

  const handleReject = async (transferId: string) => {
    try {
      const response = await fetch(
        "http://localhost:8000/api/transfer/update.php",
        {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            id: transferId,
            status: "Rejected",
          }),
        }
      );

      const data = await response.json();

      if (data.success) {
        await fetchTransfers(); // Refresh the list
        setShowApprovalModal(false);
        setSelectedTransfer(null);
      } else {
        alert("Failed to reject transfer: " + (data.error || "Unknown error"));
      }
    } catch (error) {
      console.error("Error rejecting transfer:", error);
      alert("Failed to reject transfer. Please try again.");
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading...</p>
        </div>
      </div>
    );
  }

  if (!user) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <p className="text-gray-600">Please login to access this page.</p>
        </div>
      </div>
    );
  }

  const filteredTransfers = transfers.filter(
    (transfer) => filterStatus === "" || transfer.status === filterStatus
  );

  return (
    <div className="min-h-screen bg-gray-50">
      <Header user={user} onLogout={handleLogout} />

      <main className="px-6 py-8">
        <div className="max-w-7xl mx-auto">
          <div className="flex justify-between items-center mb-8">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">
                Asset Transfers
              </h1>
              <p className="text-gray-600 mt-2">
                Manage asset transfer requests and approvals
              </p>
            </div>
            <div className="flex space-x-3">
              <button
                onClick={generatePDF}
                className="bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition duration-200 flex items-center space-x-2 whitespace-nowrap cursor-pointer"
              >
                <div className="w-5 h-5 flex items-center justify-center">
                  <i className="ri-file-pdf-line"></i>
                </div>
                <span>Export PDF</span>
              </button>
              <Link
                href="/transfers/new"
                className="bg-bs-green text-white px-4 py-2 rounded-lg hover:bg-green-700 transition duration-200 flex items-center space-x-2 whitespace-nowrap cursor-pointer"
              >
                <div className="w-5 h-5 flex items-center justify-center">
                  <i className="ri-add-line"></i>
                </div>
                <span>New Transfer</span>
              </Link>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-2xl font-bold text-yellow-600">
                    {transfers.filter((t) => t.status === "Pending").length}
                  </p>
                  <p className="text-gray-600 text-sm">Pending</p>
                </div>
                <div className="w-12 h-12 bg-yellow-100 rounded-lg flex items-center justify-center">
                  <i className="ri-time-line text-yellow-600 text-xl"></i>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-2xl font-bold text-green-600">
                    {transfers.filter((t) => t.status === "Approved").length}
                  </p>
                  <p className="text-gray-600 text-sm">Approved</p>
                </div>
                <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center">
                  <i className="ri-check-line text-green-600 text-xl"></i>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-2xl font-bold text-blue-600">
                    {transfers.filter((t) => t.status === "Completed").length}
                  </p>
                  <p className="text-gray-600 text-sm">Completed</p>
                </div>
                <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                  <i className="ri-check-double-line text-blue-600 text-xl"></i>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-2xl font-bold text-red-600">
                    {transfers.filter((t) => t.status === "Rejected").length}
                  </p>
                  <p className="text-gray-600 text-sm">Rejected</p>
                </div>
                <div className="w-12 h-12 bg-red-100 rounded-lg flex items-center justify-center">
                  <i className="ri-close-line text-red-600 text-xl"></i>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 mb-6">
            <div className="flex justify-between items-center">
              <h2 className="text-lg font-semibold text-gray-900">
                Filter Transfers
              </h2>
              <select
                value={filterStatus}
                onChange={(e) => setFilterStatus(e.target.value)}
                className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm pr-8"
              >
                <option value="">All Status</option>
                <option value="Pending">Pending</option>
                <option value="Approved">Approved</option>
                <option value="Rejected">Rejected</option>
                <option value="Completed">Completed</option>
              </select>
            </div>
          </div>

          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <div className="overflow-x-auto">
              {filteredTransfers.length === 0 ? (
                <div className="text-center py-12">
                  <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                    <i className="ri-exchange-line text-gray-400 text-2xl"></i>
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">
                    No transfers found
                  </h3>
                  <p className="text-gray-600 mb-6">
                    No transfer requests match your current filters.
                  </p>
                  <Link
                    href="/transfers/new"
                    className="bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition duration-200 inline-flex items-center space-x-2 cursor-pointer whitespace-nowrap"
                  >
                    <div className="w-5 h-5 flex items-center justify-center">
                      <i className="ri-add-line"></i>
                    </div>
                    <span>Create New Transfer</span>
                  </Link>
                </div>
              ) : (
                <table className="w-full border-collapse">
                  <thead>
                    <tr className="border-b border-gray-200">
                      <th className="text-left py-3 px-2 font-medium text-gray-700">
                        Asset Name
                      </th>
                      <th className="text-left py-3 px-2 font-medium text-gray-700">
                        Request Date
                      </th>
                      <th className="text-left py-3 px-2 font-medium text-gray-700">
                        Status
                      </th>
                      <th className="text-right py-3 px-2 font-medium text-gray-700">
                        Actions
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredTransfers.map((transfer) => (
                      <tr
                        key={transfer.id}
                        className="border-b border-gray-100 hover:bg-gray-50"
                      >
                        <td className="py-4 px-2">
                          <div>
                            <p className="font-medium text-gray-900">
                              {transfer.asset_name || "Unknown Asset"}
                            </p>
                            <p className="text-sm text-gray-500">
                              {transfer.asset_tag || "N/A"}
                            </p>
                            <div className="flex items-center space-x-1 text-xs text-gray-500 mt-1">
                              <span>{transfer.from_department}</span>
                              <i className="ri-arrow-right-line"></i>
                              <span>{transfer.to_department}</span>
                            </div>
                          </div>
                        </td>
                        <td className="py-4 px-2">
                          <p className="text-sm text-gray-900">
                            {new Date(
                              transfer.request_date
                            ).toLocaleDateString()}
                          </p>
                          <p className="text-xs text-gray-500">
                            By: {transfer.requested_by_name || "Unknown"}
                          </p>
                        </td>
                        <td className="py-4 px-2">
                          <span
                            className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${
                              transfer.status === "Pending"
                                ? "bg-yellow-100 text-yellow-800"
                                : transfer.status === "Approved"
                                ? "bg-green-100 text-green-800"
                                : transfer.status === "Rejected"
                                ? "bg-red-100 text-red-800"
                                : "bg-blue-100 text-blue-800"
                            }`}
                          >
                            {transfer.status}
                          </span>
                        </td>
                        <td className="py-4 px-2">
                          <div className="flex justify-end space-x-2">
                            <button
                              onClick={() => handleViewDetails(transfer)}
                              className="bg-blue-600 text-white px-3 py-1 rounded hover:bg-blue-700 transition duration-200 text-xs"
                              title="View Details"
                            >
                              <i className="ri-eye-line"></i>
                            </button>
                            {transfer.status === "Pending" &&
                              (user?.role === "admin" ||
                                user?.role === "procurement_officer") && (
                                <>
                                  <button
                                    onClick={() => handleApprove(transfer.id)}
                                    className="bg-green-600 text-white px-3 py-1 rounded hover:bg-green-700 transition duration-200 text-xs"
                                    title="Approve"
                                  >
                                    <i className="ri-check-line"></i>
                                  </button>
                                  <button
                                    onClick={() => handleReject(transfer.id)}
                                    className="bg-red-600 text-white px-3 py-1 rounded hover:bg-red-700 transition duration-200 text-xs"
                                    title="Reject"
                                  >
                                    <i className="ri-close-line"></i>
                                  </button>
                                </>
                              )}
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          </div>
        </div>
      </main>

      {/* Transfer Details Modal */}
      {showDetailsModal && selectedTransfer && (
        <div
          className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50"
          onClick={() => setShowDetailsModal(false)}
        >
          <div
            className="relative top-20 mx-auto p-5 border w-11/12 md:w-3/4 lg:w-1/2 shadow-lg rounded-md bg-white"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex justify-between items-center pb-4 border-b">
              <h3 className="text-lg font-bold text-gray-900">
                Transfer Details
              </h3>
              <button
                className="text-black close-button text-3xl leading-none font-semibold outline-none focus:outline-none"
                onClick={() => setShowDetailsModal(false)}
              >
                <span className="bg-transparent text-black h-6 w-6 text-2xl block outline-none focus:outline-none">
                  ×
                </span>
              </button>
            </div>

            <div className="mt-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Asset Tag
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedTransfer.asset_tag || "TUM/IT/COMP/003-25"}
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Asset Name
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedTransfer.asset_name || "Unknown Asset"}
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      From Department
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedTransfer.from_department}
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      To Department
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedTransfer.to_department}
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Status
                    </label>
                    <span
                      className={`inline-flex px-3 py-1 text-sm font-medium rounded-full ${
                        selectedTransfer.status === "Pending"
                          ? "bg-yellow-100 text-yellow-800"
                          : selectedTransfer.status === "Approved"
                          ? "bg-green-100 text-green-800"
                          : selectedTransfer.status === "Rejected"
                          ? "bg-red-100 text-red-800"
                          : "bg-blue-100 text-blue-800"
                      }`}
                    >
                      {selectedTransfer.status}
                    </span>
                  </div>
                </div>

                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Request Date
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {new Date(
                        selectedTransfer.request_date
                      ).toLocaleDateString()}
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Requested By
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedTransfer.requested_by_name || "Unknown"}
                    </p>
                  </div>

                  {selectedTransfer.approved_date && (
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Date Processed
                      </label>
                      <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                        {new Date(
                          selectedTransfer.approved_date
                        ).toLocaleDateString()}
                      </p>
                    </div>
                  )}

                  {selectedTransfer.approved_by && (
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Approved By
                      </label>
                      <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                        {selectedTransfer.approved_by}
                      </p>
                    </div>
                  )}
                </div>
              </div>

              <div className="mt-6">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Transfer Reason
                </label>
                <div className="bg-gray-50 p-3 rounded-md">
                  <p className="text-sm text-gray-900">
                    {selectedTransfer.reason ||
                      "Department restructuring - Asset needed in destination department for operational requirements"}
                  </p>
                </div>
              </div>

              <div className="mt-4">
                <div className="bg-blue-50 border border-blue-200 rounded-md p-3">
                  <div className="flex">
                    <div className="flex-shrink-0">
                      <i className="ri-exchange-line text-blue-400 text-lg"></i>
                    </div>
                    <div className="ml-3">
                      <h3 className="text-sm font-medium text-blue-800">
                        Transfer Process
                      </h3>
                      <p className="mt-1 text-sm text-blue-700">
                        Asset will be transferred from{" "}
                        {selectedTransfer.from_department} to{" "}
                        {selectedTransfer.to_department} department upon
                        approval. This transfer ensures optimal asset
                        utilization across departments.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex justify-end mt-6 pt-4 border-t">
              <button
                className="bg-gray-500 text-white px-4 py-2 rounded-lg hover:bg-gray-600 transition duration-200"
                onClick={() => setShowDetailsModal(false)}
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
