"use client";

import { useState, useEffect } from "react";
import { useSearchParams } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import Header from "@/components/Header";
import Link from "next/link";

interface AssetRequest {
  id: string;
  requester_id: string;
  requester_name: string;
  requester_email: string;
  requester_department: string;
  asset_name: string;
  asset_category: string;
  asset_description?: string;
  justification: string;
  estimated_cost?: number;
  urgency: string;
  preferred_vendor?: string;
  budget_code?: string;
  expected_delivery_date?: string;
  status: "pending" | "approved" | "rejected" | "fulfilled";
  admin_notes?: string;
  created_at: string;
  updated_at: string;
}

export default function RequestsPage() {
  const [user, setUser] = useState(getCurrentUser());
  const [requests, setRequests] = useState<AssetRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState({
    pending: 0,
    approved: 0,
    rejected: 0,
    fulfilled: 0,
  });
  const searchParams = useSearchParams();

  const handleLogout = () => {
    localStorage.removeItem("currentUser");
    window.location.href = "/";
  };

  useEffect(() => {
    if (user) {
      fetchRequests();
    }
  }, [user, searchParams]);

  const fetchRequests = async () => {
    try {
      const status = searchParams.get("status");
      const params = new URLSearchParams({
        user_id: user?.id || "",
        user_role: user?.role || "",
      });

      if (status) {
        params.append("status", status);
      }

      const response = await fetch(
        `http://localhost:8000/api/asset-requests/index.php?${params}`
      );
      const data = await response.json();

      if (data.success) {
        setRequests(data.requests);
        setStats(data.stats);
      } else {
        console.error("Failed to fetch requests:", data.error);
      }
    } catch (error) {
      console.error("Error fetching requests:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleUpdateRequest = async (
    requestId: string,
    action: "approve" | "reject"
  ) => {
    try {
      const response = await fetch(
        "http://localhost:8000/api/asset-requests/update.php",
        {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            id: requestId,
            action: action,
            user_role: user?.role,
            admin_id: user?.id,
          }),
        }
      );

      const data = await response.json();

      if (data.success) {
        // Update the request in the local state
        setRequests((prevRequests) =>
          prevRequests.map((req) =>
            req.id === requestId ? { ...req, status: data.status } : req
          )
        );
      } else {
        console.error("Failed to update request:", data.error);
        alert(`Error: ${data.error}`);
      }
    } catch (error) {
      console.error("Error updating request:", error);
    }
  };

  const generatePDF = async () => {
    try {
      // Dynamic import for client-side only
      const jsPDF = (await import("jspdf")).default;
      await import("jspdf-autotable");

      const doc = new jsPDF();

      // Add logo
      const logoResponse = await fetch("/logo.png");
      const logoData = await logoResponse.blob();
      const reader = new FileReader();
      reader.readAsDataURL(logoData);
      reader.onloadend = () => {
        const base64data = reader.result;
        doc.addImage(base64data, "PNG", 14, 15, 30, 30);

        // Add header
        const pageWidth = doc.internal.pageSize.getWidth();
        doc.setFontSize(20);
        doc.text("TUM Procurement System", pageWidth / 2, 22, {
          align: "center",
        });
        doc.setFontSize(16);
        doc.text("Asset Requests Report", pageWidth / 2, 32, {
          align: "center",
        });

        // Add generation date
        doc.setFontSize(10);
        doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 42, {
          align: "left",
        });
        doc.text(`Generated by: ${user?.name || "Unknown User"}`, 14, 48, {
          align: "left",
        });

        let yPosition = 58;
        
        // Get current data
        const currentData = requests;

        // Prepare table data
        const tableData = currentData.map((request) => [
          request.asset_name,
          request.requester_name,
          request.status,
          request.urgency,
          request.estimated_cost ? `KES ${request.estimated_cost.toLocaleString()}`: "-",
          new Date(request.created_at).toLocaleDateString(),
        ]);

        // Add table
        (doc as any).autoTable({
          head: [
            [
              "Asset",
              "Requester",
              "Status",
              "Urgency",
              "Cost",
              "Requested",
            ],
          ],
          body: tableData,
          startY: yPosition,
          styles: {
            fontSize: 8,
            cellPadding: 2,
          },
          headStyles: {
            fillColor: [220, 53, 69],
            textColor: 255,
            fontStyle: "bold",
          },
          margin: { top: yPosition, right: 14, bottom: 20, left: 14 },
          didDrawPage: function (data: any) {
            // Footer
            const str = `Page ${data.pageNumber}`;
            doc.setFontSize(10);
            const pageSize = doc.internal.pageSize;
            const pageHeight = pageSize.height
              ? pageSize.height
              : pageSize.getHeight();
            doc.text(str, data.settings.margin.left, pageHeight - 10);

            // Total count
            if (data.pageNumber === 1) {
              doc.text(
                `Total Requests: ${
                  currentData.length
                }`,
                pageSize.width - 60,
                pageHeight - 10
              );
            }
          },
        });

        // Save the PDF
        const fileName = `TUM_Asset_Requests_Report_${
          new Date().toISOString().split("T")[0]
        }.pdf`;
        doc.save(fileName);
      };
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("Failed to generate PDF. Please try again.");
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "pending":
        return "bg-yellow-100 text-yellow-800";
      case "approved":
        return "bg-green-100 text-green-800";
      case "rejected":
        return "bg-red-100 text-red-800";
      case "fulfilled":
        return "bg-blue-100 text-blue-800";
      default:
        return "bg-gray-100 text-gray-800";
    }
  };

  const getUrgencyColor = (urgency: string) => {
    switch (urgency) {
      case "Critical":
        return "bg-red-100 text-red-800";
      case "High":
        return "bg-orange-100 text-orange-800";
      case "Normal":
        return "bg-blue-100 text-blue-800";
      case "Low":
        return "bg-gray-100 text-gray-800";
      default:
        return "bg-gray-100 text-gray-800";
    }
  };

  if (!user) {
    return <div>Please login to access this page.</div>;
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Header user={user} onLogout={handleLogout} />

      <main className="px-6 py-8">
        <div className="max-w-7xl mx-auto">
          <div className="flex justify-between items-center mb-8">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">
                Asset Requests
              </h1>
              <p className="text-gray-600 mt-2">
                Manage and track asset requisition requests
              </p>
            </div>
            <div className="flex space-x-3">
              {user?.role === 'procurement_officer' && (
                <button
                  onClick={generatePDF}
                  className="bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition duration-200 flex items-center space-x-2 whitespace-nowrap cursor-pointer"
                >
                  <div className="w-5 h-5 flex items-center justify-center">
                    <i className="ri-file-pdf-line"></i>
                  </div>
                  <span>Export PDF</span>
                </button>
              )}
              <Link
                href="/requests/new"
                className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition duration-200 flex items-center space-x-2"
              >
                <i className="ri-add-line"></i>
                <span>New Request</span>
              </Link>
            </div>
          </div>

          {/* Statistics Cards */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
            <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
              <div className="flex items-center">
                <div className="p-3 rounded-full bg-yellow-100">
                  <i className="ri-time-line text-yellow-600 text-xl"></i>
                </div>
                <div className="ml-4">
                  <p className="text-sm font-medium text-gray-600">Pending</p>
                  <p className="text-2xl font-semibold text-gray-900">
                    {stats.pending}
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
              <div className="flex items-center">
                <div className="p-3 rounded-full bg-green-100">
                  <i className="ri-check-line text-green-600 text-xl"></i>
                </div>
                <div className="ml-4">
                  <p className="text-sm font-medium text-gray-600">Approved</p>
                  <p className="text-2xl font-semibold text-gray-900">
                    {stats.approved}
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
              <div className="flex items-center">
                <div className="p-3 rounded-full bg-red-100">
                  <i className="ri-close-line text-red-600 text-xl"></i>
                </div>
                <div className="ml-4">
                  <p className="text-sm font-medium text-gray-600">Rejected</p>
                  <p className="text-2xl font-semibold text-gray-900">
                    {stats.rejected}
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
              <div className="flex items-center">
                <div className="p-3 rounded-full bg-blue-100">
                  <i className="ri-package-line text-blue-600 text-xl"></i>
                </div>
                <div className="ml-4">
                  <p className="text-sm font-medium text-gray-600">Fulfilled</p>
                  <p className="text-2xl font-semibold text-gray-900">
                    {stats.fulfilled}
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Requests Table */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
            {loading ? (
              <div className="flex items-center justify-center py-20">
                <div className="text-gray-500">Loading requests...</div>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead className="bg-gray-50 border-b border-gray-200">
                    <tr>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                        Asset
                      </th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                        Requester
                      </th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                        Status
                      </th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                        Urgency
                      </th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                        Cost
                      </th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                        Requested
                      </th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                        Actions
                      </th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-200">
                    {requests.length === 0 ? (
                      <tr>
                        <td
                          colSpan={7}
                          className="px-6 py-12 text-center text-gray-500"
                        >
                          <div className="flex flex-col items-center">
                            <i className="ri-inbox-line text-4xl text-gray-400 mb-4"></i>
                            <h3 className="text-lg font-medium text-gray-900 mb-2">
                              No requests found
                            </h3>
                            <p className="text-gray-600 mb-4">
                              No asset requests match the current filters.
                            </p>
                          </div>
                        </td>
                      </tr>
                    ) : (
                      requests.map((request) => (
                        <tr key={request.id} className="hover:bg-gray-50">
                          <td className="px-6 py-4">
                            <div>
                              <div className="text-sm font-medium text-gray-900">
                                {request.asset_name}
                              </div>
                            </div>
                          </td>
                          <td className="px-6 py-4">
                            <div className="text-sm font-medium text-gray-900">{request.requester_name}</div>
                            <div className="text-sm text-gray-500">{request.requester_department}</div>
                          </td>
                          <td className="px-6 py-4">
                            <span
                              className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${getStatusColor(
                                request.status
                              )}`}
                            >
                              {request.status.charAt(0).toUpperCase() +
                                request.status.slice(1)}
                            </span>
                          </td>
                          <td className="px-6 py-4">
                            <span
                              className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${getUrgencyColor(
                                request.urgency
                              )}`}
                            >
                              {request.urgency}
                            </span>
                          </td>
                          <td className="px-6 py-4 text-sm text-gray-900">
                            {request.estimated_cost
                              ? `KES ${request.estimated_cost.toLocaleString()}`
                              : "-"}
                          </td>
                          <td className="px-6 py-4 text-sm text-gray-500">
                            {new Date(request.created_at).toLocaleDateString()}
                          </td>
                          <td className="px-6 py-4">
                            <div className="flex items-center space-x-4">
                              <Link
                                href={`/requests/${request.id}`}
                                className="text-blue-600 hover:text-blue-800 text-sm"
                              >
                                <i className="ri-eye-line mr-1"></i>
                                Details
                              </Link>
                              {user?.role === 'procurement_officer' && request.status === 'pending' && (
                                <>
                                  <button
                                    onClick={() => handleUpdateRequest(request.id, 'approve')}
                                    className="text-green-600 hover:text-green-800 text-sm"
                                  >
                                    <i className="ri-check-line mr-1"></i>
                                    Approve
                                  </button>
                                  <button
                                    onClick={() => handleUpdateRequest(request.id, 'reject')}
                                    className="text-red-600 hover:text-red-800 text-sm"
                                  >
                                    <i className="ri-close-line mr-1"></i>
                                    Reject
                                  </button>
                                </>
                              )}
                            </div>
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
