"use client";

import { useState, useEffect } from "react";
import { getCurrentUser } from "@/lib/auth";
import Header from "@/components/Header";
import Link from "next/link";

interface Asset {
  id: string;
  asset_tag: string;
  name: string;
  category: string;
  department: string;
  description?: string;
  purchase_date?: string;
  purchase_price?: number;
  current_value?: number;
  condition?: string;
  location?: string;
  serial_number?: string;
  model?: string;
  brand?: string;
  status?: string;
  created_at?: string;
  updated_at?: string;
}

export default function AssetsPage() {
  const [user, setUser] = useState(getCurrentUser());
  const [assets, setAssets] = useState<Asset[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [filterDepartment, setFilterDepartment] = useState("");
  const [filterCategory, setFilterCategory] = useState("");
  const [filterStatus, setFilterStatus] = useState("");
  const [accessInfo, setAccessInfo] = useState<any>(null);
  const [showDetailsModal, setShowDetailsModal] = useState(false);
  const [selectedAsset, setSelectedAsset] = useState<Asset | null>(null);

  useEffect(() => {
    fetchAssets();
  }, [searchTerm, filterDepartment, filterCategory, filterStatus, user]);

  const fetchAssets = async () => {
    try {
      const params = new URLSearchParams();
      if (searchTerm) params.append("search", searchTerm);
      if (filterDepartment) params.append("department", filterDepartment);
      if (filterCategory) params.append("category", filterCategory);
      if (filterStatus) params.append("status", filterStatus);

      // Add user information for department-based access control
      if (user?.role) params.append("user_role", user.role);
      if (user?.department) params.append("user_department", user.department);

      const response = await fetch(
        `http://localhost:8000/api/assets/index.php?${params}`
      );
      const data = await response.json();

      if (data.success) {
        setAssets(data.assets);
        setAccessInfo(data.access_info);

        // Log access control information for debugging
        if (data.access_info) {
          console.log("Asset access info:", data.access_info);
        }
      } else {
        console.error("Failed to fetch assets:", data.error);
      }
    } catch (error) {
      console.error("Error fetching assets:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleLogout = () => {
    localStorage.removeItem("currentUser");
    window.location.href = "/";
  };

  const handleViewDetails = (asset: Asset) => {
    setSelectedAsset(asset);
    setShowDetailsModal(true);
  };

  const generatePDF = async () => {
    try {
      // Dynamic import for client-side only
      const jsPDF = (await import("jspdf")).default;
      await import("jspdf-autotable");

      const doc = new jsPDF();

      // Add header
      doc.setFontSize(20);
      doc.text("TUM Procurement System", 14, 22);
      doc.setFontSize(16);
      doc.text("Asset Management Report", 14, 32);

      // Add generation date
      doc.setFontSize(10);
      doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 42);
      doc.text(`Generated by: ${user?.name || "Unknown User"}`, 14, 48);

      // Add filters info if any are applied
      let yPosition = 58;
      if (searchTerm || filterDepartment || filterCategory || filterStatus) {
        doc.setFontSize(12);
        doc.text("Applied Filters:", 14, yPosition);
        yPosition += 8;
        doc.setFontSize(10);

        if (searchTerm) {
          doc.text(`Search: ${searchTerm}`, 14, yPosition);
          yPosition += 6;
        }
        if (filterDepartment) {
          doc.text(`Department: ${filterDepartment}`, 14, yPosition);
          yPosition += 6;
        }
        if (filterCategory) {
          doc.text(`Category: ${filterCategory}`, 14, yPosition);
          yPosition += 6;
        }
        if (filterStatus) {
          doc.text(`Status: ${filterStatus}`, 14, yPosition);
          yPosition += 6;
        }
        yPosition += 5;
      }

      // Prepare table data
      const tableData = assets.map((asset) => [
        asset.asset_tag,
        asset.name,
        asset.category,
        asset.department,
        asset.condition || "Unknown",
        asset.status || "Unknown",
        asset.brand || "N/A",
        asset.model || "N/A",
      ]);

      // Add table
      (doc as any).autoTable({
        head: [
          [
            "Asset Tag",
            "Name",
            "Category",
            "Department",
            "Condition",
            "Status",
            "Brand",
            "Model",
          ],
        ],
        body: tableData,
        startY: yPosition,
        styles: {
          fontSize: 8,
          cellPadding: 2,
        },
        headStyles: {
          fillColor: [66, 139, 202],
          textColor: 255,
          fontStyle: "bold",
        },
        columnStyles: {
          0: { cellWidth: 20 }, // Asset Tag
          1: { cellWidth: 25 }, // Name
          2: { cellWidth: 20 }, // Category
          3: { cellWidth: 20 }, // Department
          4: { cellWidth: 18 }, // Condition
          5: { cellWidth: 18 }, // Status
          6: { cellWidth: 18 }, // Brand
          7: { cellWidth: 18 }, // Model
        },
        margin: { top: yPosition, right: 14, bottom: 20, left: 14 },
        didDrawPage: function (data: any) {
          // Footer
          const str = `Page ${data.pageNumber}`;
          doc.setFontSize(10);
          const pageSize = doc.internal.pageSize;
          const pageHeight = pageSize.height
            ? pageSize.height
            : pageSize.getHeight();
          doc.text(str, data.settings.margin.left, pageHeight - 10);

          // Total count
          if (data.pageNumber === 1) {
            doc.text(
              `Total Assets: ${assets.length}`,
              pageSize.width - 50,
              pageHeight - 10
            );
          }
        },
      });

      // Save the PDF
      const fileName = `TUM_Assets_Report_${
        new Date().toISOString().split("T")[0]
      }.pdf`;
      doc.save(fileName);
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("Failed to generate PDF. Please try again.");
    }
  };

  if (!user) {
    return <div>Please login to access this page.</div>;
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Header user={user} onLogout={handleLogout} />

      <main className="px-6 py-8">
        <div className="max-w-7xl mx-auto">
          <div className="flex justify-between items-center mb-8">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">
                Asset Management
              </h1>
              <p className="text-gray-600 mt-2">
                Manage and track all organizational assets
              </p>
            </div>
            <div className="flex space-x-3">
              <button
                onClick={generatePDF}
                className="bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition duration-200 flex items-center space-x-2 whitespace-nowrap cursor-pointer"
              >
                <div className="w-5 h-5 flex items-center justify-center">
                  <i className="ri-file-pdf-line"></i>
                </div>
                <span>Export PDF</span>
              </button>
              <Link
                href="/assets/import"
                className="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition duration-200 flex items-center space-x-2 whitespace-nowrap cursor-pointer"
              >
                <div className="w-5 h-5 flex items-center justify-center">
                  <i className="ri-file-excel-line"></i>
                </div>
                <span>Import Excel</span>
              </Link>
              <Link
                href="/assets/new"
                className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition duration-200 flex items-center space-x-2 whitespace-nowrap cursor-pointer"
              >
                <div className="w-5 h-5 flex items-center justify-center">
                  <i className="ri-add-line"></i>
                </div>
                <span>Add Asset</span>
              </Link>
            </div>
          </div>

          {/* Access Control Indicator */}
          {accessInfo?.restricted_access && (
            <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-6">
              <div className="flex items-center">
                <div className="flex-shrink-0">
                  <i className="ri-information-line text-amber-600 text-lg"></i>
                </div>
                <div className="ml-3">
                  <h3 className="text-sm font-medium text-amber-800">
                    Department Restricted Access
                  </h3>
                  <p className="text-sm text-amber-700 mt-1">
                    You are viewing assets from your department (
                    {accessInfo?.user_department}) only. Contact an
                    administrator or procurement officer for access to other
                    department assets.
                  </p>
                </div>
              </div>
            </div>
          )}

          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 mb-6">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Search
                </label>
                <div className="relative">
                  <input
                    type="text"
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    placeholder="Search by name or tag..."
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm"
                  />
                  <div className="absolute inset-y-0 right-0 pr-3 flex items-center">
                    <div className="w-4 h-4 flex items-center justify-center">
                      <i className="ri-search-line text-gray-400"></i>
                    </div>
                  </div>
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Department
                </label>
                <select
                  value={filterDepartment}
                  onChange={(e) => setFilterDepartment(e.target.value)}
                  disabled={accessInfo?.restricted_access}
                  className={`w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm pr-8 ${
                    accessInfo?.restricted_access
                      ? "bg-gray-100 cursor-not-allowed"
                      : ""
                  }`}
                >
                  {accessInfo?.restricted_access ? (
                    <option value="">
                      {accessInfo?.user_department} (Your Department)
                    </option>
                  ) : (
                    <>
                      <option value="">All Departments</option>
                      <option value="IT">IT</option>
                      <option value="Finance">Finance</option>
                      <option value="HR">HR</option>
                      <option value="Engineering">Engineering</option>
                      <option value="Marketing">Marketing</option>
                      <option value="Procurement">Procurement</option>
                      <option value="Operations">Operations</option>
                      <option value="Sales">Sales</option>
                      <option value="Legal">Legal</option>
                      <option value="Admin">Admin</option>
                    </>
                  )}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Category
                </label>
                <select
                  value={filterCategory}
                  onChange={(e) => setFilterCategory(e.target.value)}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm pr-8"
                >
                  <option value="">All Categories</option>
                  <option value="Computers">Computers</option>
                  <option value="Furniture">Furniture</option>
                  <option value="Equipment">Equipment</option>
                  <option value="Vehicles">Vehicles</option>
                  <option value="Software">Software</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Status
                </label>
                <select
                  value={filterStatus}
                  onChange={(e) => setFilterStatus(e.target.value)}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm pr-8"
                >
                  <option value="">All Status</option>
                  <option value="Active">Active</option>
                  <option value="Transferred">Transferred</option>
                  <option value="Disposed">Disposed</option>
                  <option value="Pending Disposal">Pending Disposal</option>
                  <option value="Under Maintenance">Under Maintenance</option>
                </select>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
            {loading ? (
              <div className="flex items-center justify-center py-20">
                <div className="text-gray-500">Loading assets...</div>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead className="bg-gray-50 border-b border-gray-200">
                    <tr>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                        Asset Tag
                      </th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                        Name
                      </th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                        Category
                      </th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                        Department
                      </th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                        Condition
                      </th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                        Status
                      </th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                        Actions
                      </th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-200">
                    {assets.length === 0 ? (
                      <tr>
                        <td
                          colSpan={7}
                          className="px-6 py-12 text-center text-gray-500"
                        >
                          No assets found
                        </td>
                      </tr>
                    ) : (
                      assets.map((asset) => (
                        <tr key={asset.id} className="hover:bg-gray-50">
                          <td className="px-6 py-4 text-sm font-medium text-gray-900">
                            {asset.asset_tag}
                          </td>
                          <td className="px-6 py-4">
                            <div>
                              <div className="text-sm font-medium text-gray-900">
                                {asset.name}
                              </div>
                              <div className="text-sm text-gray-500">
                                {asset.brand} {asset.model}
                              </div>
                            </div>
                          </td>
                          <td className="px-6 py-4 text-sm text-gray-900">
                            {asset.category}
                          </td>
                          <td className="px-6 py-4 text-sm text-gray-900">
                            {asset.department}
                          </td>
                          <td className="px-6 py-4">
                            <span
                              className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${
                                asset.condition === "Excellent"
                                  ? "bg-green-100 text-green-800"
                                  : asset.condition === "Good"
                                  ? "bg-blue-100 text-blue-800"
                                  : asset.condition === "Fair"
                                  ? "bg-yellow-100 text-yellow-800"
                                  : asset.condition === "Poor"
                                  ? "bg-orange-100 text-orange-800"
                                  : asset.condition === "Obsolete"
                                  ? "bg-red-100 text-red-800"
                                  : "bg-gray-100 text-gray-800"
                              }`}
                            >
                              {asset.condition || "Unknown"}
                            </span>
                          </td>
                          <td className="px-6 py-4">
                            <span
                              className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${
                                asset.status === "Active"
                                  ? "bg-green-100 text-green-800"
                                  : asset.status === "Disposed"
                                  ? "bg-red-100 text-red-800"
                                  : asset.status === "Transferred"
                                  ? "bg-blue-100 text-blue-800"
                                  : asset.status === "Pending Disposal" ||
                                    asset.status === "Disposal Pending"
                                  ? "bg-orange-100 text-orange-800"
                                  : "bg-yellow-100 text-yellow-800"
                              }`}
                            >
                              {asset.status || "Unknown"}
                            </span>
                          </td>
                          <td className="px-6 py-4">
                            <div className="flex space-x-2">
                              <button
                                onClick={() => handleViewDetails(asset)}
                                className="text-blue-600 hover:text-blue-800 cursor-pointer"
                                title="View Details"
                              >
                                <div className="w-5 h-5 flex items-center justify-center">
                                  <i className="ri-eye-line"></i>
                                </div>
                              </button>
                              <Link
                                href={`/assets/${asset.id}/edit`}
                                className="text-green-600 hover:text-green-800 cursor-pointer"
                              >
                                <div className="w-5 h-5 flex items-center justify-center">
                                  <i className="ri-edit-line"></i>
                                </div>
                              </Link>
                              <Link
                                href={`/transfers/new?asset=${asset.id}`}
                                className="text-yellow-600 hover:text-yellow-800 cursor-pointer"
                              >
                                <div className="w-5 h-5 flex items-center justify-center">
                                  <i className="ri-exchange-line"></i>
                                </div>
                              </Link>
                            </div>
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          <div className="mt-6 flex justify-between items-center">
            <p className="text-sm text-gray-700">
              Showing {assets.length} assets
            </p>
            <div className="flex space-x-2">
              <button className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-700 hover:bg-gray-50 cursor-pointer whitespace-nowrap">
                Previous
              </button>
              <button className="px-3 py-2 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-700 cursor-pointer whitespace-nowrap">
                1
              </button>
              <button className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-700 hover:bg-gray-50 cursor-pointer whitespace-nowrap">
                Next
              </button>
            </div>
          </div>
        </div>
      </main>

      {/* Asset Details Modal */}
      {showDetailsModal && selectedAsset && (
        <div
          className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50"
          onClick={() => setShowDetailsModal(false)}
        >
          <div
            className="relative top-20 mx-auto p-5 border w-11/12 md:w-3/4 lg:w-2/3 xl:w-1/2 shadow-lg rounded-md bg-white"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex justify-between items-center pb-4 border-b">
              <h3 className="text-lg font-bold text-gray-900">Asset Details</h3>
              <button
                className="text-black close-button text-3xl leading-none font-semibold outline-none focus:outline-none"
                onClick={() => setShowDetailsModal(false)}
              >
                <span className="bg-transparent text-black h-6 w-6 text-2xl block outline-none focus:outline-none">
                  ×
                </span>
              </button>
            </div>

            <div className="mt-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Asset Tag
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedAsset.asset_tag}
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Asset Name
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedAsset.name}
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Category
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedAsset.category}
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Department
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedAsset.department}
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Brand
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedAsset.brand || "N/A"}
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Model
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedAsset.model || "N/A"}
                    </p>
                  </div>
                </div>

                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Serial Number
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedAsset.serial_number || "N/A"}
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Location
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedAsset.location || "N/A"}
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Condition
                    </label>
                    <span
                      className={`inline-flex px-3 py-1 text-sm font-medium rounded-full ${
                        selectedAsset.condition === "Excellent"
                          ? "bg-green-100 text-green-800"
                          : selectedAsset.condition === "Good"
                          ? "bg-blue-100 text-blue-800"
                          : selectedAsset.condition === "Fair"
                          ? "bg-yellow-100 text-yellow-800"
                          : selectedAsset.condition === "Poor"
                          ? "bg-orange-100 text-orange-800"
                          : selectedAsset.condition === "Obsolete"
                          ? "bg-red-100 text-red-800"
                          : "bg-gray-100 text-gray-800"
                      }`}
                    >
                      {selectedAsset.condition || "Unknown"}
                    </span>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Status
                    </label>
                    <span
                      className={`inline-flex px-3 py-1 text-sm font-medium rounded-full ${
                        selectedAsset.status === "Active"
                          ? "bg-green-100 text-green-800"
                          : selectedAsset.status === "Disposed"
                          ? "bg-red-100 text-red-800"
                          : selectedAsset.status === "Transferred"
                          ? "bg-blue-100 text-blue-800"
                          : selectedAsset.status === "Pending Disposal" ||
                            selectedAsset.status === "Disposal Pending"
                          ? "bg-orange-100 text-orange-800"
                          : "bg-yellow-100 text-yellow-800"
                      }`}
                    >
                      {selectedAsset.status || "Unknown"}
                    </span>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Purchase Date
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedAsset.purchase_date
                        ? new Date(
                            selectedAsset.purchase_date
                          ).toLocaleDateString()
                        : "N/A"}
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Purchase Price
                    </label>
                    <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                      {selectedAsset.purchase_price
                        ? `$${selectedAsset.purchase_price.toLocaleString()}`
                        : "N/A"}
                    </p>
                  </div>
                </div>
              </div>

              {selectedAsset.description && (
                <div className="mt-6">
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Description
                  </label>
                  <div className="bg-gray-50 p-3 rounded-md">
                    <p className="text-sm text-gray-900">
                      {selectedAsset.description}
                    </p>
                  </div>
                </div>
              )}

              <div className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Current Value
                  </label>
                  <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                    {selectedAsset.current_value
                      ? `$${selectedAsset.current_value.toLocaleString()}`
                      : "N/A"}
                  </p>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Last Updated
                  </label>
                  <p className="text-sm text-gray-900 bg-gray-50 p-2 rounded">
                    {selectedAsset.updated_at
                      ? new Date(selectedAsset.updated_at).toLocaleDateString()
                      : "N/A"}
                  </p>
                </div>
              </div>
            </div>

            <div className="flex justify-between mt-6 pt-4 border-t">
              <div className="flex space-x-3">
                <Link
                  href={`/assets/${selectedAsset.id}/edit`}
                  className="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition duration-200 flex items-center space-x-2"
                  onClick={() => setShowDetailsModal(false)}
                >
                  <i className="ri-edit-line"></i>
                  <span>Edit Asset</span>
                </Link>
                <Link
                  href={`/transfers/new?asset=${selectedAsset.id}`}
                  className="bg-yellow-600 text-white px-4 py-2 rounded-lg hover:bg-yellow-700 transition duration-200 flex items-center space-x-2"
                  onClick={() => setShowDetailsModal(false)}
                >
                  <i className="ri-exchange-line"></i>
                  <span>Transfer Asset</span>
                </Link>
              </div>
              <button
                className="bg-gray-500 text-white px-4 py-2 rounded-lg hover:bg-gray-600 transition duration-200"
                onClick={() => setShowDetailsModal(false)}
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
